version: '3.8'
services: 
  web: 
    build:
      context: '.'
      target: production
    volumes: 
      - ./:/src
#      - /Users/zuzel/Projects/nodejs-docker-express:/src
    ports: 
      - "3000:3000"
    environment:
      NODE_ENV: production

      

    
    