version: '3.8'
services: 
  web: 
    build:
      context: '.'
      target: production
    volumes: 
      - .:/src
    ports: 
      - "3000:3000"
    environment:
      NODE_ENV: production
      

    
    