version: '3.8'
services: 
  web: 
    build:
      context: '.'
      target: production
    volumes: 
      - ./:/src
#      - /Users/zuzel/Projects/nodejs-docker-express:/src
    ports: 
      - "3001:3000"
    environment:
      NODE_ENV: dev
  cypress:
    image: 'cypress/included:9.0.0'
    depends_on:
      - "web"
    volumes: 
      - ./:./

      

    
    